labels:
  cashflow:
    - ItemType
    - SubItemType
    - module
    - rule

  pnl:
    - ItemType
    - SubItemType
    - module
    - rule

  oci:
    - ItemType
    - SubItemType
    - module
    - rule

profitability_outlooks:
  - Monthly
  - Quarterly
  - Annual
